language: node_js
dist: xenial
services:
  - xvfb
sudo: true
node_js:
  - "8"

script: npm run $COMMAND

env:
  matrix:
  - COMMAND=test
  - CLIENT=selenium:firefox COMMAND=test
  - COMMAND=coverage
branches:
  only:
  - master
